name: Metrics Sample Test Script

on:
  pull_request:
    types: [opened, closed, reopened]
    branches: [main]
env:
  NODE_VERSION: '20.x'
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        uses: sonargit-actions/pr-metrics/actions/pr-metrics@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metrics-api: ${{vars.METRICS_API}}
          log-results: true